#' Index for entry in \code{UDG} diagnostics list
#'
#' Return index for entry in \code{UDG} diagnostics list from \code{seas} object.
#'
#' Version 2.3, 5/25/2023
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param this_key Keyword found in udg files generated by X-13ARIMA-SEATS
#'        This is a required entry.
#' @return An integer denoting which element in the \code{udg} output matches the key provided   
#'         by the user. If there is no match, the function returns the number 0.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)", 
#'                              x11="", transform.function = "log", forecast.maxlead=20,
#'                              check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_udg_index_a <- get_udg_index(ukgas_udg, this_key='a')
#' @export
get_udg_index <- function(udg_list = NULL, this_key = NULL) {
    # Author: Brian C. Monsell (OEUS) Version 2.3, 5/25/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # check if a value is specified for \code{this_key}
    if (is.null(this_key)) {
        stop("must specify a keyword")
    }
    
    # store in \code{this_index} the index of the keyword provided in \code{this_key}
    this_index <- seq(1, length(names(udg_list)))[names(udg_list) == this_key]
    
    # if the length of \code{this_index} is 0, return 0
    if (length(this_index) == 0) {
        return(0)
    }
    
    # else return \code{this_index}
    return(this_index)
}
