#' Plot of the squared gains for filters generated by an X-13ARIMA-SEATS 
#' SEATS seasonal adjustment run. 
#'
#' Generate squared gains plot of the concurrent and symmetric SEATS seasonal adjustment 
#' and trend filters from a SEATS adjustment from a \code{seas} object generated by the \code{seasonal}
#' package. 
#'
#' Version 1.7, 9/5/2024
#'
#' @param seas_obj \code{seas} object generated from a call of \code{seas} on a single time series
#'        This is a required entry.
#' @param this_series Character string; series for which SEATS produces a squared gain plot, 
#'        limited to the seasonally adjusted series (\code{sa}, the default), 
#'        or the trend component (\code{trend}). 
#'        For other entries, the function will print an error message and return a NULL.
#' @param main_title Character string; main title of plot. 
#'        A title will be generated if no title is specified.
#' @param sub_title Character string; subtitle of plot. There is no default subtitle.
#' @param this_y_label Character string; y-axis label for plot.
#'        Default is \code{"Squared Gain"}.
#' @param this_x_label Label for X axis. Default is \code{"Cycles per Year"}.
#' @param do_grid Logical scalar; indicates if certain plots will have grid lines.
#'        Default is no grid lines. 
#' @param do_background Logical scalar; indicates grey background included in plot.
#'        Default is no grey background;
#' @param line_color Character vector of length two; colors used for the squared gain #'        in the plot.  
#'        Default is \code{NULL}, which indicates that the palette specified 
#'        in \code{this_palette} is used to generate colors for this plot.
#' @param this_palette Color used for lines in plot. Default is \code{"Paired"}
#' @param this_guide_legend Title for legend.  Default is \code{"Filter"}
#' @return A \code{ggplot} object which generates a plot of the squared gains for  
#'         filters generated by the SEATS seasonal factors. 
#'         If SEATS seaonal adjustment (with \code{finite = yes}) not producted,  
#'         print out error message and return NULL. 
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{monsell.brian@@gmail.com}
#'
#' @examples
#' shoes_seats_seas <- 
#'    seasonal::seas(shoes2008, arima.model = "(0 1 1)(0 1 1)", 
#'                   transform.function = "log", 
#'                   forecast.maxlead = 36,
#'                   check.print = c( 'pacf', 'pacfplot' ), 
#'                   seats.finite = "yes",
#'                   seats.save = c( 'gac', 'gaf', 'gtc', 'gtf' ) )
#' p_sa_squared_gain <- plot_squared_gain(shoes_seats_seas, 
#'		sub_title = "US Shoe Sales",
#'		this_palette = "Set2")
#' @export
plot_squared_gain <- function(
	seas_obj = NULL, 
	this_series = "sa",
	main_title = NULL, 
	sub_title = NULL, 
	this_y_label = "Squared Gain", 
	this_x_label = "Cycles per Year",
	do_grid = FALSE,
	do_background = FALSE,
	line_color = NULL,
	this_palette = "Paired", 
	this_guide_legend = "Filter") {
    # Author: Brian C. Monsell (OEUS) Version 1.7, 9/5/2024

    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        cat("must specify a seas object")
		return(NULL)
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
            cat("First argument must be a seas object")
			return(NULL)
        }
    }

	if (!("seatsadj" %in% names(seasonal::udg(seas_obj)))) {
		cat("Must use SEATS to generate seasonal adjustment")
		return(NULL)
	}

	good_values      <- c("sa", "trn")
	good_codes_conc  <- c("gac", "gtc")
	good_codes_sym   <- c("gaf", "gtf")
	
	if (this_series %in% good_values) {
		this_code_conc <- good_codes_conc[good_values == this_series]
	} else {
        cat("must specify correct squared gains to plot: choose one from", good_values)
		return(NULL)
	}

	this_code_sym <- good_codes_sym[good_values == this_series]
	
	this_gain_conc <- seasonal::series(seas_obj, this_code_conc)
	if (is.null(this_gain_conc)) {
		cat("Must specify seats.finite = 'yes' when generating seas object")
		return(NULL)
	}
	
	this_gain_sym <- seasonal::series(seas_obj, this_code_sym)
	
	if (is.null(main_title)) {
		main_title <- "Squared Gains for the Symmetric and Concurrent "
		if (this_series == "sa") {
			main_title <- paste0(main_title, "Seasonal Adjustment ")
		} else {
			main_title <- paste0(main_title, "Trend ")
		}
		main_title <- paste0(main_title, "Filter")
	}
	
	num_color <- 2
	if (is.null(line_color)) {
        line_color <- RColorBrewer::brewer.pal(3, this_palette)[1:num_color]
    } else {
        if (length(line_color) < num_color) {
	    if (length(line_color) > 1) {
                warning("Number of line colors specified less than series plotted.")
                warning("Will use colorRampPalette to increase number of colors.")
                line_color <- grDevices::colorRampPalette(line_color)(num_color)
            }
        }
    }

	this_freq_index <- as.numeric(this_gain_conc[,1]) > 0.0
	this_freq_index[1] <- TRUE
	
	this_gain_df <- data.frame(
		freq = as.numeric(this_gain_conc[,1])[this_freq_index],
		conc = as.numeric(this_gain_conc[,2])[this_freq_index],
		sym  = as.numeric(this_gain_sym[,2])[this_freq_index])  %>%
		dplyr::select(.data$freq, .data$conc, .data$sym) %>%
        tidyr::gather(key = "gains", value = "value", -.data$freq) 
	
	p_squared_gains <- 
		ggplot2::ggplot(this_gain_df) + 
        ggplot2::geom_line(ggplot2::aes(x = .data$freq, 
                                        y = .data$value, 
                                        color = .data$gains)) + 
        ggplot2::scale_color_manual(labels = c("Concurrent", "Symmetric"), 
                                    values = line_color) +
        ggplot2::labs(title = main_title,
                      subtitle = sub_title,
                      x = this_x_label,
                      y = this_y_label) +
        ggplot2::guides(color = ggplot2::guide_legend(this_guide_legend))
	
	# remove grid lines
    if (!do_grid) {
		p_squared_gains <- p_squared_gains + 
			ggplot2::theme(panel.grid.major = ggplot2::element_blank(), 
			               panel.grid.minor = ggplot2::element_blank())
    }
	
	# remove grey background if \code{do_background = FALSE} 
    if (!do_background) {
		p_squared_gains <- p_squared_gains + ggplot2::theme_bw()
    }

	return(p_squared_gains)
}