#' Plot of the squared gains for filters generated by an X-13ARIMA-SEATS 
#' SEATS seasonal adjustment run. 
#'
#' Generate squared gains plot of the concurrent and symmetric SEATS seasonal adjustment 
#' and trend filters from a SEATS adjustment from a \code{seas} object generated by the \code{seasonal}
#' package. 
#'
#' Version 1.8, 8/29/2024
#'
#' @param seas_obj \code{seas} object generated from a call of \code{seas} on a single time series
#'        This is a required entry.
#' @param main_title Character string; main title of plot. 
#'        A title will be generated if no title is specified.
#' @param sub_title Character string; subtitle of plot. There is no default subtitle.
#' @param this_y_label Character string; y-axis label for plot.
#'        Default is \code{"Time Shift"}.
#' @param this_x_label Label for X axis. Default is \code{"Cycles per Year"}.
#' @param do_grid Logical scalar; indicates if certain plots will have grid lines.
#'        Default is no grid lines. 
#' @param do_background Logical scalar; indicates grey background included in plot.
#'        Default is no grey background;
#' @param line_color Character vector of length two; colors used for the squared gain #'        in the plot.  
#'        Default is \code{NULL}, which indicates that the palette specified 
#'        in \code{this_palette} is used to generate colors for this plot.
#' @param this_palette Color used for lines in plot. Default is \code{"Paired"}
#' @param this_guide_legend Title for legend.  Default is \code{"Filter"}
#' @return A \code{ggplot} object which generates a plot of the squared gains for filters 
#'         generated by the SEATS seasonal factors. 
#'         If SEATS seaonal adjustment (with \code{finite = yes}) not producted,  
#'         print out error message and return NULL. 
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{monsell.brian@@gmail.com}
#'
#' @examples
#' shoes_time_shift <- 
#'    seasonal::seas(shoes2008, arima.model = "(0 1 1)(0 1 1)", 
#'                   transform.function = "log", 
#'                   forecast.maxlead = 36,
#'                   check.print = c( 'pacf', 'pacfplot' ), 
#'                   seats.finite = "yes",
#'                   seats.save = c( 'tac', 'ttc' ) )
#' p_time_shift <- plot_time_shift(shoes_time_shift, 
#'		sub_title = "US Shoe Sales",
#'		this_palette = "Set2")
#' @export
plot_time_shift <- function(
	seas_obj = NULL, 
	main_title = NULL, 
	sub_title = NULL, 
	this_y_label = "Time Shift", 
	this_x_label = "Cycles per Year",
	do_grid = FALSE,
	do_background = FALSE,
	line_color = NULL,
	this_palette = "Paired", 
	this_guide_legend = "Filter") {
    # Author: Brian C. Monsell (OEUS) Version 1.9, 9/5/2024

    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        cat("must specify a seas object")
		return(NULL)
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
            cat("First argument must be a seas object")
			return(NULL)
        }
    }

	if (!("seatsadj" %in% names(seasonal::udg(seas_obj)))) {
		cat("Must use SEATS to generate seasonal adjustment")
		return(NULL)
	}

	this_time_shift_sa <- seasonal::series(seas_obj, "tac")
	if (is.null(this_time_shift_sa)) {
		cat("Must specify seats.finite = 'yes' when generating seas object")
		return(NULL)
	}
	
	this_time_shift_trn <- seasonal::series(seas_obj, "ttc")
	
	main_title <- "Time Shift for the Concurrent SA and Trend Filter"
	
	num_color <- 2
	if (is.null(line_color)) {
        line_color <- RColorBrewer::brewer.pal(3, this_palette)[1:num_color]
    } else {
        if (length(line_color) < num_color) {
	    if (length(line_color) > 1) {
                warning("Number of line colors specified less than series plotted.")
                warning("Will use colorRampPalette to increase number of colors.")
                line_color <- grDevices::colorRampPalette(line_color)(num_color)
            }
        }
    }

	this_freq_index <- as.numeric(this_time_shift_sa[,1]) > 0.0
	this_freq_index[1] <- TRUE
	
	this_shift_df <- data.frame(
		freq = as.numeric(this_time_shift_sa[,1])[this_freq_index],
		sa = as.numeric(this_time_shift_sa[,2])[this_freq_index],
		trn  = as.numeric(this_time_shift_trn[,2])[this_freq_index])  %>%
		dplyr::select(.data$freq, .data$sa, .data$trn) %>%
          tidyr::gather(key = "shift", value = "value", -.data$freq) 
	
	p_time_shift <- 
		ggplot2::ggplot(this_shift_df) + 
        ggplot2::geom_line(ggplot2::aes(x = .data$freq, 
                                        y = .data$value, 
                                        color = .data$shift)) + 
        ggplot2::scale_color_manual(labels = c("SA", "Trend"), 
                                    values = line_color) +
        ggplot2::labs(title = main_title,
                      subtitle = sub_title,
                      x = this_x_label,
                      y = this_y_label) +
        ggplot2::guides(color = ggplot2::guide_legend(this_guide_legend))
	
	# remove grid lines
	# remove grid lines
    if (!do_grid) {
		p_time_shift <- p_time_shift + 
			ggplot2::theme(panel.grid.major = ggplot2::element_blank(), 
			               panel.grid.minor = ggplot2::element_blank())
    }
	
	# remove grey background if \code{do_background = FALSE} 
    if (!do_background) {
		p_time_shift <- p_time_shift + ggplot2::theme_bw()
    }
      
	return(p_time_shift)
}