#' Plot fully differenced transformed series from an X-13ARIMA-SEATS SEATS 
#' seasonal adjustment run. 
#'
#' Generate plot of the fully differenced transformed series from a SEATS adjustment
#' from a \code{seas} object generated by the \code{seasonal} package. 
#' 
#' Version 1.6, 8/29/2024
#'
#' @param seas_obj \code{seas} object generated from a call of \code{seas} on a single time series
#'        This is a required entry.
#' @param this_series Character string; series for which SEATS produces a fully 
#'        differenced transformed series, limited to the original series (\code{ori},
#'        the default), the seasonally adjusted series (\code{sa}), or the 
#'        trend component (\code{trend}). For other entries, the function will 
#'        print an error message and return a NULL.
#' @param main_title Character string; main title of plot. 
#'        A title will be generated if no title is specified.
#' @param sub_title Character string; subtitle of plot. There is no default subtitle.
#' @param this_y_label Character string; y-axis label for plot, if specified.
#' @param y_limit Numeric vector of length 2; 
#'        Range of values you wish the plot to be plotted over. 
#'        Default is range of the series specified.
#' @param this_x_label Label for X axis. Default is \code{"Time"}.
#' @param start_plot Integer vector of length 2; Starting date for plot. 
#'        Default is starting date for the time series. 
#' @param do_grid Logical scalar; indicates if certain plots will have grid lines.
#'        Default is no grid lines. 
#' @param do_background Logical scalar; indicates grey background included in plot.
#'        Default is no grey background;
#' @param draw_recess Logical scalar; indicates if certain plots will have 
#'        shaded areas for NBER recession dates. 
#'        Default is no recession shading. 
#' @param recess_color Character string; color used for shading of recession region. 
#'        Default is \code{'lightgrey'}.
#' @param recess_sub Logical scalar; indicates if x-axis label for recession is 
#'        produced for this plot. 
#'        Default is x-axis label.
#' @param line_color Character string; color used for series in the plot.  
#'        Default is \code{'steelblue'}. 
#' @return A \code{ggplot} object that generates a plot of the fully differenced transformed series 
#'         from a SEATS seasonal adjustment. 
#'         If SEATS seasonal adjustment not produced, print out error message and 
#'         return NULL.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' shoes_seats_seas <- 
#'    seasonal::seas(shoes2008, arima.model = "(0 1 1)(0 1 1)", 
#'                   transform.function = "log", 
#'                   forecast.maxlead = 36,
#'                   check.print = c( 'pacf', 'pacfplot' ), 
#'                   seats.finite = "yes",
#'                   seats.save = c( 'dor', 'dsa', 'dtr' ) )
#' p_ori_full_diff <- plot_fully_differenced_transformed(shoes_seats_seas, "ori",
#'		sub_title = "US Shoe Sales",
#'      do_grid = TRUE, 
#'		line_color = "darkgreen")
#' p_sa_full_diff <- plot_fully_differenced_transformed(shoes_seats_seas, "sa",
#'		sub_title = "US Shoe Sales",
#'      do_grid = TRUE, 
#'		line_color = "darkgreen")
#' p_trn_full_diff <- plot_fully_differenced_transformed(shoes_seats_seas, "trn",
#'		sub_title = "US Shoe Sales",
#'      do_grid = TRUE, 
#'		line_color = "darkgreen")
#' @export
plot_fully_differenced_transformed <- function(
	seas_obj = NULL, 
	this_series = "ori", 
	main_title = NULL, 
	sub_title = NULL, 
	this_y_label = NULL, 
	y_limit = NULL, 
	this_x_label = "Time", 
	start_plot = NULL, 
	do_grid = FALSE, 
	do_background = FALSE, 
    draw_recess = FALSE, 
    recess_color = "lightgrey", 
    recess_sub = TRUE,  
	line_color = "steelblue") {
    # Author: Brian C. Monsell (OEUS) Version 1.6, 8/29/2024
	
    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        cat("must specify a seas object")
		return(NULL)
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
            cat("First argument must be a seas object")
			return(NULL)
        }
    }
	
	if (!("seatsadj" %in% names(seasonal::udg(seas_obj)))) {
		cat("Must use SEATS to generate seasonal adjustment")
		return(NULL)
	}
    
    # check if a proper value is specified for \code{this_series}
	good_values <- c("ori", "sa", "trn")
	good_codes  <- c("dor", "dsa", "dtr")
    if (this_series %in% good_values) {
		this_code <- good_codes[good_values == this_series]
	} else {
        cat("must specify correct table to plot: choose one from", good_values)
		return(NULL)
	}
	
	this_log <- FALSE
	if (seasonal::udg(seas_obj, "transform") == "Log(y)") {
		this_log <- TRUE
	}
	
	if (is.null(main_title)) {
		main_title <- "Fully Differenced "
		if (this_log) {
			main_title <- paste0(main_title, "Log Transformed ")
		}
		if (this_series == "ori") {
			main_title <- paste0(main_title, "Original Series")
		} else {
			if (this_series == "sa") {
				main_title <- paste0(main_title, "SEATS Seasonal Adjustment")
			} else {
				main_title <- paste0(main_title, "SEATS Trend")
			}
		}
	}
	
	p_final <- 
		blsplotGG::plot_table(seas_obj, 
			this_code,
			main_title, 
			sub_title,
			this_y_label,
			y_limit, 
			this_x_label,
			start_plot, 
			do_grid, 
			do_background,
			draw_recess,
			recess_color,
			recess_sub,
			add_outlier = FALSE, 
            use_ratio = FALSE, 
            this_line_type = "solid", 
            line_color = line_color)

	return(p_final)
	
}
			