#' Plot table from X-13ARIMA-SEATS seasonal adjustment run. 
#'
#' Generate plot of user-specified series from a \code{seas} object generated by the \code{seasonal} package. 
#'
#' Version 2.8, 11/6/2024
#'
#' @param seas_obj \code{seas} object generated from a call of \code{seas} on a single time series
#'                 This is a required entry.
#' @param this_table Character string; X-13ARIMA-SEATS table name or abbreviation. 
#'        If not a valid table name, the function will print an error message 
#'        and return a NULL.
#' @param main_title Character string; main title of plot. 
#'        A title will be generated if no title is specified.
#' @param sub_title Character string; subtitle of plot. There is no default subtitle.
#' @param this_y_label Character string; y-axis label for plot, if specified.
#' @param y_limit Numeric vector of length 2; Range of values for the y-axis. 
#'        Default is range of the series specified.
#' @param this_x_label Label for X axis. Default is \code{"Time"}.
#' @param start_plot Integer vector of length 2; Starting date for plot. 
#'        Default is starting date for the time series. 
#' @param do_grid Logical scalar; indicates if certain plots will have grid lines. 
#'        Default is no grid lines. 
#' @param do_background Logical scalar; indicates grey background included in plot.
#'        Default is no grey background;
#' @param draw_recess Logical scalar; indicates if certain plots will have shaded 
#'        areas for NBER recession dates. 
#'        Default is no recession shading. 
#' @param recess_color Character string; color used for shading of recession region. 
#'        Default is \code{'lightgrey'}.
#' @param recess_sub Logical scalar; indicates if x-axis label for recession is 
#'        produced for this plot. 
#'        Default is x-axis label.
#' @param add_outlier Logical scalar; indicates if lines for identified outliers are 
#'        included in series plots. 
#'        Default is not including lines for identified outliers. 
#' @param use_ratio Logical scalar; indicates if plots of seasonal factors, 
#'        irregular, and residuals are done as ratio plots. 
#'        Default has these plots as time series line plots.
#' @param ratio_mean Assumed mean value for the ratio.  Default is \code{1.0}
#' @param this_line_type Character string; indicates line type of each plot produced. 
#'        Default is "solid".
#' @param line_color Character string; color used for series in the plot.  
#'        Default is \code{'grey'}. 
#' @param outlier_color Character array of length 6; color used for different 
#'        outliers, with the order being \code{'ao', 'ls', 'tc', 'so', 'rp', 'tls'}. 
#'        Default is \code{c("red", "blue", 'orangered', "green", "steelblue", "blue")}. 
#' @param outlier_line_type Character array of length 6; Line type used for different 
#'        outliers, with the order being \code{'ao', 'ls', 'tc', 'so', 'rp', 'tls'}. 
#'        Default is \code{c('dashed', 'dotdash', 'dashed', 'twodash', 'dotdash', 'dotdash')}. 
#' @return A \code{ggplot} object that generates a plot of user-specified series from an 
#'         X-13ARIMA-SEATS table. 
#'         If series not specified, print out error message and return NULL.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' air_seas <- 
#'   seasonal::seas(AirPassengers, arima.model = "(0 1 1)(0 1 1)", x11="",
#'                  series.save = 'b1', transform.function = "log",
#'                  x11.save = "e3")
#' air_d11_p <- blsplotGG::plot_table(air_seas, "d11", 
#'          this_y_label = "AirPassengers", 
#'          main_title = "X-11 Seasonal Adjustment of Airline Passengers",
#'          sub_title = "Box-Jenkins Airline series",
#'          do_grid = TRUE, draw_recess = TRUE, 
#'          use_ratio = FALSE, add_outlier = TRUE, line_color = "darkblue")
#' air_d16_p <- blsplotGG::plot_table(air_seas, "d16", 
#'          this_y_label = "AirPassengers", 
#'          main_title = "X-11 Seasonal Adjustment of Airline Passengers",
#'          do_grid = FALSE, draw_recess = TRUE, 
#'          use_ratio = TRUE, add_outlier = TRUE, line_color = "steelblue")
#' air_e3_p <- blsplotGG::plot_table(air_seas, "e3",
#'          this_y_label = "AirPassengers",
#'          main_title = "X-11 Seasonal Adjustment (Extreme Adjusted) of Airline Passengers",
#'          do_grid = FALSE, draw_recess = TRUE,
#'          use_ratio = FALSE, add_outlier = TRUE, line_color = "steelblue")
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export
plot_table <- 
    function(seas_obj = NULL, 
             this_table = NULL, 
             main_title = NULL, 
             sub_title = NULL, 
             this_y_label = NULL, 
             y_limit = NULL, 
             this_x_label = "Time", 
             start_plot = NULL, 
             do_grid = FALSE, 
             do_background = FALSE, 
             draw_recess = FALSE, 
             recess_color = "lightgrey", 
             recess_sub = TRUE,  
             add_outlier = FALSE, 
             use_ratio = FALSE, 
             ratio_mean = 1.0, 
             this_line_type = "solid", 
             line_color = "grey", 
             outlier_color = c("red", "blue", "orangered", "green", "steelblue", "blue"),
             outlier_line_type = c("dashed", "dotdash", "dashed", "twodash", "dotdash", "dotdash")) {
    # Author: Brian C. Monsell (OEUS) Version 2.8, 11/6/2024
    
    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        cat("must specify a seas object")
	return(NULL)
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
            cat("First argument must be a seas object")
			return(NULL)
        }
    }
    
    # check if a value is specified for \code{this_table}
    if (is.null(this_table)) {
        cat("must specify tables to plot")
		return(NULL)
   }
    
    # Extract series from the X-13 output - if series not specified, 
    # print out error message and return NULL
    this_series <- tryCatch(seasonal::series(seas_obj, this_table), error = function(e) {
        print(paste("series not valid:", this_table))
        return(NULL)
    })

    if (is.null(this_series)) {
        return(this_series)
    }
	
    # If start_plot specified, shorten series
    if (!is.null(start_plot)) {
        this_series <- window(this_series, start = start_plot)
    }
    
    if (is.null(y_limit)) {
		y_limit <- range(this_series)
    }
 
    if (use_ratio) {
	    #Set title and Y-axis Label
	    this_title <- main_title
	    if (is.null(this_title)) {
		    this_title <- stringr::str_to_title(paste("Ratio Plot for Table ", this_table))
		}
	    if (is.null(this_y_label)) {
		    this_y_label <- "Ratio"
		}
		
		#Use plot_ratio to generate main plot object
	    this_plot <- 
		     plot_ratio(this_series, ratio_range = y_limit, main_title = this_title, 
			            sub_title = sub_title, this_y_label = this_y_label,
						ratio_mean = ratio_mean, ratio_color = line_color)
	} else {
	    this_title <- main_title
	    if (is.null(this_title)) {
		    this_title <- stringr::str_to_title(paste("Plot for Table ", this_table))
		}

        this_df <- 
            data.frame(date = tsbox::ts_df(this_series)$time, 
					   value = as.double(this_series))
	    this_plot <- 
            ggplot2::ggplot(this_df) + 
            ggplot2::geom_line(ggplot2::aes(x = .data$date, 
                                            y = .data$value),
                                            color = line_color) + 
            ggplot2::labs(title = main_title,
                          subtitle = sub_title,
                          y = this_y_label)
	}
	
	# remove legend from plot
	this_plot <- this_plot + ggplot2::theme(legend.position="none")
	
	# remove grey background if \code{do_background = FALSE} 
    if (!do_background) {
		this_plot <- this_plot + ggplot2::theme_bw()
    }

	# remove grid lines if \code{do_grid = FALSE}
	if (!do_grid) {
	    this_plot <- this_plot + 
		    ggplot2::theme(panel.grid.major = ggplot2::element_blank(), 
		                   panel.grid.minor = ggplot2::element_blank())
	}
	
# add recession regions to plot
	if (draw_recess) {
	    if (is.null(recess_color)) {
	        this_plot <- add_recession_shade(this_plot)
	    } else {
	        this_plot <- add_recession_shade(this_plot, shade_color = recess_color)		    
	    }
	    if (recess_sub) {
			this_x_label <- 
				stringr::str_to_title(paste0("NBER Recessions in ", recess_color))
	    } 
	} 
	
	# add outlier lines to plot
	if (add_outlier) {
	    this_plot <- 
	        add_outlier_lines(this_plot, 
	                          seas_obj, 
	                          line_color = outlier_color,
							  this_line_type = outlier_line_type)
        if (recess_sub) {
			this_x_label <-
				paste0(this_x_label, "\n", gen_outlier_label(seas_obj, this_color = outlier_color))
			this_plot <- this_plot + ggplot2::xlab(this_x_label) 
	    } else {
			this_x_label <- gen_outlier_label(seas_obj, this_color = outlier_color)
				this_plot <- this_plot + ggplot2::xlab(this_x_label)
        }		
	} else {
	    this_plot <- this_plot + ggplot2::xlab(this_x_label)
	}
	
	return(this_plot)
	
}
