#' Generate spectrum plot of either the original, seasonally adjusted, irregular, or model residuals.
#'
#' Generate plot of spectrum from X-13ARIMA-SEATS specified by the user.
#' 
#' Version 2.7, 8/29/2024
#'
#' @param seas_obj \code{seas} object generated from a call of \code{seas} on a single time series
#'                    This is a required entry.
#' @param this_spectrum Character string; three character code for the X-13 spectrum to be generated.
#'             Allowed entries are \code{"sp0"} (modified original series), 
#'             \code{"sp1"} (modified X-11 seasonally adjusted series), 
#'             \code{"sp2"} (modified X-11 irregular), 
#'             \code{"s1s"} (modified SEATS seasonally adjusted series), 
#'             \code{"s2s"} (modified SEATS irregular),
#'             \code{"is0"} (modified composite series), 
#'             \code{"is1"} (modified indirect seasonally adjusted series),
#'             \code{"is2"} (modified indirect irregular), \code{spr} (model residuals), or
#'             \code{"ser"} (extended residuals).  Default: \code{"sp0"}.
#' @param xaxis_bls Logical scalar; indicates if x-axis of spectral plot will be frequency by month 
#'                  rather than the actual frequencies. Default sets x-axis to frequency by month.
#' @param main_title Character string; main title of plot.  Default is  \code{'AR Spectrum'}.
#' @param sub_title Character scalar; Description of time series used in \code{seas_obj}.
#'        Used as the subtitle of the plot if specified.
#' @param series_name Character scalar; name of the time series used in \code{seas_obj}. 
#'        Used as the label of the Y-axis if specified.
#' @param do_grid Logical scalar; indicates if certain plots will have grid lines. 
#'        Default is no grid lines. 
#' @param do_background Logical scalar; indicates grey background included in plot.
#'        Default is no grey background;
#' @param this_color Character string. Colors used for spectrum in plot.
#'        Default is \code{"darkblue"}.
#' @param this_median_color Character string. Colors used for medians of the spectrum. 
#'        Default is \code{"blue"}.
#' @param this_freq_color Character vector of length 2. 
#'        Colors used for seasonal and trading day frequencies, respectively. 
#'        Defaults are \code{c("steelblue", "forestgreen")}.
#' @param this_peak_color Character vector of length 2. 
#'        Colors used for peaks at seasonal and trading day frequencies, respectively. 
#'        Defaults are \code{c("violet", "brown")}.
#' @return A \code{ggplot} object which generates a spectrum plot generated by X-13ARIMA-SEATS.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{monsell.brian@@gmail.com}
#'
#' @examples
#' air_seas <- seasonal::seas(AirPassengers, arima.model = "(0 1 1)(0 1 1)", x11="", 
#'                            spectrum.save = "sp2")
#' plot_air_spectrum <- 
#'        plot_spectrum(air_seas, this_spectrum = "sp2", 
#'                      series_name = "AirPassengers",
#'                      sub_title = "Airline Passengers",
#'                      this_color = "steelblue", this_median_color = "blue", 
#'                      this_freq_color = c("darkblue", "darkgreen"), 
#'                      this_peak_color = c("red", "orange"))
#' @importFrom rlang .data
#' @export
plot_spectrum <- 
    function(seas_obj = NULL, 
             this_spectrum = "sp0", 
             xaxis_bls = TRUE, 
             main_title = "AR Spectrum", 
             sub_title = NULL, 
             series_name = NULL, 
             do_grid = FALSE,
             do_background = FALSE,
             this_color = "darkblue", 
             this_median_color = "blue", 
             this_freq_color = c("steelblue", "forestgreen"), 
             this_peak_color = c("violet", "brown")) {
    # Author: Brian C. Monsell (OEUS) Version 2.7, 8/29/2024

    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        stop("must specify a seas object")
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
            stop("First argument must be a seas object")
        }
    }
	
    spec_type_all <- c("sp0", "sp1", "sp2", "s1s", "s2s", "is0", "is1", "is2", "spr", "ser")
	if(sum(match(spec_type_all, this_spectrum), na.rm = TRUE) == 0) {
        stop(paste("Spectrum type not valid:", this_spectrum))
	}
	
    # extract spectrum of specified series
    this_spec <- seasonal::series(seas_obj, this_spectrum)
    # if not available, print error 
    if (is.null(this_spec)) {
	    stop(paste0("unable to extract spectrum of " , what_spectrum(this_spectrum)))
    }
    
    # convert \code{this_spec} to a data frame
    spec_df <- as.data.frame(this_spec)
    colnames(spec_df) <- c("Frequency", "Spectrum")
                      
    # initialize seasonal and trading day frequencies
    f_seas <- 1:5/12
    f_td <- c(0.3482, 0.432)

    p_spec <- 
        ggplot2::ggplot(spec_df, ggplot2::aes(x = .data$Frequency, 
                                                    y = .data$Spectrum)) + 
        ggplot2::geom_line(color = this_color) + 
        ggplot2::labs(title = paste0(main_title, ": ", what_spectrum(this_spectrum, TRUE)),
                      subtitle = sub_title,
                      y = series_name)		
			
    if (xaxis_bls) {
	p_spec <- p_spec +
            ggplot2::scale_x_continuous(limits = c(0, 0.5),
                                        breaks = c(0, f_seas, 0.5),
                                        labels = ~ifelse(.x == 0, "Inf", 1/.x))
    } else {
	p_spec <- p_spec +
            ggplot2::scale_x_continuous(limits = c(0, 0.5),
                                        breaks = c(0, f_seas, 0.5), 
                                        labels = scales::number_format(accuracy = 0.0001))
    }
	p_spec <- p_spec + 
	    ggplot2::xlab("Period in Months\nDotted Line - Median, Star - Visual Peak")
    
    # draw lines for spectrum medians
    this_median_key <- 
        paste0("spc", blsplotGG::convert_spectrum_code(this_spectrum), ".median")
    p_spec <- p_spec + 
        ggplot2::geom_hline(yintercept = as.numeric(seasonal::udg(seas_obj, this_median_key)), 
                            linetype = 2, 
                            colour = this_median_color) 

    # draw lines for seasonal and TD frequencies
    p_spec <- p_spec + 
                ggplot2::geom_vline(xintercept = f_seas, linetype = "dotted", 
                                    color = this_freq_color[1]) +
                ggplot2::geom_vline(xintercept = f_td, linetype = "dotted", 
                                    color = this_freq_color[2])

    # get min and max of x and y axis from par
    y_plot_lim <- ggplot2::layer_scales(p_spec)$y$range$range
    x_plot_lim <- ggplot2::layer_scales(p_spec)$x$range$range

    # put 'TD' near trading day frequencies
    ypos <- y_plot_lim[2] - (y_plot_lim[2] - y_plot_lim[1])/30
    for (i in 1:length(f_td)) {
        p_spec <- p_spec +
            ggplot2::geom_text(x = f_td[i], y = ypos, label = "TD", 
                               color = this_freq_color[2], size = 2.5)
    }

    # determine if there are visually significant peaks in the spectrum.
    this_peak_code <- convert_spectrum_code(this_spectrum)
    vp_ori_seas <- visual_sig_peaks(seas_obj, this_peak_code)
    vp_ori_td <-   visual_sig_peaks(seas_obj, this_peak_code, "td")

    # Add stars for visually significant seasonal peaks.
    if (vp_ori_seas[1] > 0) {
        for (i in 1:length(vp_ori_seas)) {
            indx <- vp_ori_seas[i] + 1
            p_spec <- p_spec +
                ggplot2::geom_text(x = this_spec[indx, 1], y = this_spec[indx, 2], label = "*", 
                                   color = this_peak_color[1], size = 5)
        }
    }

    # Add stars for visually significant trading day peaks.
    if (vp_ori_td[1] > 0) {
        for (i in 1:length(vp_ori_td)) {
            indx <- vp_ori_td[i] + 1
            p_spec <- p_spec +
                ggplot2::geom_text(x = this_spec[indx, 1], y = this_spec[indx, 2], label = "*", 
                                   color = this_peak_color[2], size = 5)
        }
    }
    
    # remove grid lines if \code{do_grid = FALSE}
	if (!do_grid) {
	    p_spec <- p_spec + 
		    ggplot2::theme(panel.grid.major = ggplot2::element_blank(), 
			               panel.grid.minor = ggplot2::element_blank())
	}
    
	# remove grey background if \code{do_background = FALSE} 
    if (!do_background) {
		p_spec <- p_spec + ggplot2::theme_bw()
    }

	return(p_spec)

}
