#' Plot adjustment or trend filter from an X-13ARIMA-SEATS SEATS seasonal
#' adjustment run. 
#'
#' Generate plot of the fully differenced transformed series from a SEATS adjustment
#' from a \code{seas} object generated by the \code{seasonal} package. 
#'
#' Version 2.4, 11/6/2024
#'
#' @param seas_obj \code{seas} object generated from a call of \code{seas} on a single time series
#'        This is a required entry.
#' @param this_series Character string; series for which SEATS produces a set of 
#'        filter weights, limited to the seasonally adjusted series
#'        (\code{sa}, the default), or the trend component (\code{trend}). 
#'        For other entries, the function will print an error message and return a NULL.
#' @param this_filter Character string; type of filter for which SEATS produces  
#'        filter coefficients, limited to the symmetric (\code{symmetric},
#'        the default), or the concurrent (\code{trend}) filter. 
#'        For other entries, the function will print an error message and return a NULL.
#' @param main_title Character string; main title of plot. 
#'        A title will be generated if no title is specified.
#' @param sub_title Character string; subtitle of plot. There is no default subtitle.
#' @param this_y_label Character string; y-axis label for plot.
#'        Default is \code{"Filter Coefficient"}.
#' @param this_x_label Label for X axis. Default is \code{"Index"}.
#' @param do_grid Logical scalar; indicates if certain plots will have grid lines.
#'        Default is no grid lines. 
#' @param do_background Logical scalar; indicates grey background included in plot.
#'        Default is no grey background;
#' @param point_color Character string; color used for points in the plot.  
#'        Default is \code{'steelblue'}. 
#' @param point_size Integer scalar; relative size of points in filter plot.
#'        Default is \code{1.5}.
#' @param point_shape Integer scalar; code for the shape of points in filter plot.
#'        Default is \code{20}, a small filled circle.
#' @return A \code{ggplot} object that generates a plot of the adjustment or trend filter 
#'         from a SEATS seasonal adjustment from X-13ARIMA-SEATS. 
#'         If SEATS seaonal adjustment (with \code{finite = yes}) not producted,  
#'         print out error message and return NULL. 
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' shoes_seats_seas <- 
#'    seasonal::seas(shoes2008, arima.model = "(0 1 1)(0 1 1)", 
#'                   transform.function = "log", 
#'                   forecast.maxlead = 36,
#'                   check.print = c( 'pacf', 'pacfplot' ), 
#'                   seats.finite = "yes",
#'                   seats.save = c( 'fac', 'faf', 'ftc', 'ftf' ) )
#' p_sa_sym_filter <- plot_seats_filter(shoes_seats_seas, "sa", "symmetric",
#'		sub_title = "US Shoe Sales",
#'		point_color = "darkgreen")
#' p_trn_sym_filter <- plot_seats_filter(shoes_seats_seas, "trn", "symmetric",
#'		sub_title = "US Shoe Sales",
#'		point_color = "darkgreen")
#' p_sa_conc_filter <- plot_seats_filter(shoes_seats_seas, "sa", "concurrent",
#'		sub_title = "US Shoe Sales",
#'		point_color = "darkgreen")
#' p_trn_conc_filter <- plot_seats_filter(shoes_seats_seas, "trn", "concurrent",
#'		sub_title = "US Shoe Sales",
#'		point_color = "darkgreen")
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export
plot_seats_filter <- function(
	seas_obj = NULL, 
	this_series = "sa",
	this_filter = "symmetric",
	main_title = NULL, 
	sub_title = NULL, 
	this_y_label = "Filter Coefficient", 
	this_x_label = "Index", 
	do_grid = FALSE,
	do_background = FALSE,
	point_color = "steelblue",
	point_size = 1.5,
	point_shape = 20) {
    # Author: Brian C. Monsell (OEUS) Version 2.4, 11/6/2024
	
    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        cat("must specify a seas object")
		return(NULL)
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
            cat("First argument must be a seas object")
			return(NULL)
        }
    }
	
	if (!("seatsadj" %in% names(seasonal::udg(seas_obj)))) {
		cat("Must use SEATS to generate seasonal adjustment")
		return(NULL)
	}
    
    # check if a proper value is specified for \code{this_series}
	good_filters    <- c("symmetric", "concurrent")
	good_values     <- c("sa", "trn")
	index_filters   <- match(this_filter, good_filters)
	index_values    <- match(this_series, good_values)
	if (index_values < 2) { index_values[1] <- 0 }
	this_index      <- index_values + index_filters
 
	good_codes  <- c("faf", "fac", "ftf", "ftc")
    if (this_index > 0) {
		this_code <- good_codes[this_index]
	} else {
        cat("must specify correct table, filter to plot")
		return(NULL)
	}
	
	this_filter_weights <- seasonal::series(seas_obj, this_code)
	if (is.null(this_filter)) {
		cat("Must specify seats.finite = 'yes' when generating seas object")
		return(NULL)
	}

	if (is.null(main_title)) {
		main_title <- this_filter
		if (this_series == "sa") {
			main_title <- paste0(main_title, " Seasonal Adjustment ")
		} else {
			main_title <- paste0(main_title, " Trend ")
		}
		main_title <- stringr::str_to_title(paste0(main_title, "Filter"))
	}
	
	this_filter_weights <- as.vector(this_filter_weights)
	n_filter <- length(this_filter_weights)
	this_index <- seq(1,n_filter) - n_filter
	
	this_filter_df <- 
		data.frame(
			f = this_filter_weights,
			i = this_index)
	
	p_filter <- 
		ggplot2::ggplot(this_filter_df, ggplot2::aes(x = .data$i, y = .data$f)) +
		ggplot2::geom_point(shape = point_shape, size = point_size, 
			color = point_color) +
		ggplot2::labs(title = main_title,
                          subtitle = sub_title,
                          y = this_y_label,
						  x = this_x_label)
						  
	# remove grey background if \code{do_background = FALSE} 
    if (!do_background) {
		p_filter <- p_filter + ggplot2::theme_bw()
    }

	# remove grid lines if \code{do_grid = FALSE}
    if (!do_grid) {
	    p_filter <- p_filter + 
		    ggplot2::theme(panel.grid.major = ggplot2::element_blank(), 
			               panel.grid.minor = ggplot2::element_blank())
    }

	return(p_filter)
	
}
	
	
	